import type { Metadata } from "next";
import { Geist, Geist_Mono , Telex , Slabo_13px,Anton} from "next/font/google";
import "./globals.css";
import ScrollContext from "@/components/ScrollContext";
import Cursor from "@/components/Cursor";
const slabo = Slabo_13px({
  variable: "--font-slabo",
  subsets: ["latin"],
  weight: "400"
})

const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400"
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const telex = Telex({
  variable: "--font-telex",
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Pushpahas WebWork's",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${telex.variable} ${slabo.variable} ${anton.variable} antialiased scroll-smooth`}
      >
         <ScrollContext>
         
        <Cursor />
        {children}
        
        </ScrollContext>
      </body>
    </html>
  );
}
